- name: Redmicaのソースコードを取得
  become: yes
  ansible.builtin.git:
    repo={{ redmica_git_url }}
    dest={{ redmica_dir }}

- name: Redmineディレクトリ以下のオーナーを変更
  become: yes
  file:
    path: "{{ redmica_dir }}"
    owner: "{{ redmica_owner }}"
    group: "{{ redmica_group }}"
    recurse: yes

- name: database.ymlの作成
  # become: yes
  template:
    src=database.yml
    dest={{ redmica_dir }}/config/database.yml
    force=no
  register:
    result_database_yml

- name: configuration.ymlの作成
  # become: yes
  template:
    src=configuration.yml
    dest={{ redmica_dir }}/config/configuration.yml
    force=no

- name: Gemfile.lockが存在するか確認
  command:
    test -f {{ redmica_dir }}/Gemfile.lock
  register:
    result_test_gemfile
  failed_when: result_test_gemfile.rc not in [0, 1]
  changed_when: false

- name: gemsパッケージのインストール
  # become: yes
  command:
    bundle install
    chdir={{ redmica_dir }}
  environment:
    PATH: "{{ruby_path}}:{{ ansible_env.PATH }}:/usr/pgsql-10/bin"
  when:
    result_test_gemfile.rc == 1

- name: gemsパッケージのアップデート
  # become: yes
  command:
    bundle update
    chdir={{ redmica_dir }}
  environment:
    PATH: "{{ruby_path}}:{{ ansible_env.PATH }}:/usr/pgsql-10/bin"
  when:
    result_test_gemfile.rc == 0

# - name: secret tokenの作成
#   become: yes
#   command:
#     bundle exec rake generate_secret_token
#     chdir={{ redmica_dir }}
#   environment:
#     PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
#     RAILS_ENV: production

# - name: データベースのマイグレーション
#   become: yes
#   command:
#     bundle exec rake db:migrate
#     chdir={{ redmica_dir }}
#   environment:
#     PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
#     RAILS_ENV: production

# - name: デフォルトデータ(日本語)をロード
#   become: yes
#   command:
#     bundle exec rake redmine:load_default_data
#     chdir={{ redmica_dir }}
#   environment:
#     PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
#     RAILS_ENV: production
#     REDMINE_LANG: ja
#   when:
#     result_database_yml is changed

# - name: デフォルトの言語を日本語に変更
#   become: yes
#   command:
#     bundle exec rails r 'Setting["default_language"]="ja"'
#     chdir={{ redmica_dir }}
#   environment:
#     PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
#     RAILS_ENV: production
#   when:
#     result_database_yml is changed

# - name: ユーザー名の表示形式を「姓 名」に変更
#   become: yes
#   command:
#     bundle exec rails r 'Setting["user_format"]=:lastname_firstname'
#     chdir={{ redmica_dir }}
#   environment:
#     PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
#     RAILS_ENV: production
#   when:
#     result_database_yml is changed

# - name: 添付ファイルとリポジトリのエンコーディングを設定
#   become: yes
#   command:
#     bundle exec rails r 'Setting["repositories_encodings"]="UTF-8,CP932,EUC-JP"'
#     chdir={{ redmica_dir }}
#   environment:
#     PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
#     RAILS_ENV: production
#   when:
#     result_database_yml is changed

# - name: 添付ファイルのサムネイルを表示
#   become: yes
#   command:
#     bundle exec rails r 'Setting["thumbnails_enabled"]="1"'
#     chdir={{ redmica_dir }}
#   environment:
#     PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
#     RAILS_ENV: production
#   when:
#     result_database_yml is changed
