- name: SELinuxの状態確認
  command:
    /usr/sbin/selinuxenabled
  register:
    result
  changed_when: false
  failed_when: result.rc not in [0, 1]

- name: 起動時にSELinux無効化 (/etc/sysconfig/selinux)
  become: yes
  selinux: state=disabled
  when: result.rc == 0

- name: SELinux無効化 (setenforce)
  become: yes
  command: setenforce 0
  when: result.rc == 0

- name: firewalldが起動しているか確認
  become: yes
  shell: firewall-cmd --state
  register: firewall_state
  ignore_errors: yes
  changed_when: false
  check_mode: no

- name: firewalldでHTTPを許可
  become: yes
  firewalld:
    zone=public
    service=http
    permanent=yes
    state=enabled
    immediate=yes
  when: firewall_state.rc == 0

- name: 開発ツールのインストール
  become: yes
  yum: name='@Development Tools'

- name: RubyとPassengerのビルドに必要な開発ツールやヘッダファイルのインストール
  become: yes
  yum:
    name='openssl-devel,readline-devel,zlib-devel,curl-devel,libyaml,libffi-devel'

- name: Install a yum repository file of pgdg 1/2.
  become: yes
  command: "rpm -ivh --nodeps https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
  args:
    creates: /etc/yum.repos.d/pgdg-redhat-all.repo
    warn: no

- name: Install a yum repository file of pgdg 2/2.
  become: yes
  replace: dest=/etc/yum.repos.d/pgdg-redhat-all.repo regexp='\$releasever' replace='7'

- name:  PostgreSQLとヘッダファイルのインストール
  become: yes
  yum:
    name='postgresql10-server,postgresql10,postgresql10-devel,python-psycopg2'

- name: Apacheとヘッダファイルのインストール
  become: yes
  yum:
    name='httpd,httpd-devel'

- name: ImageMagickのインストール
  become: yes
  yum:
    name='ImageMagick,ImageMagick-devel'

- name: そのほかのツールのインストール
  become: yes
  yum:
    name='subversion,git,which'

- name: 作業ディレクトリ作成
  file: path={{ work_dir }}
    state=directory
    mode=0755
